# Use an official Node.js runtime as a parent image
FROM node:18-slim

# Set the working directory
WORKDIR /usr/src/app

# Install dependencies for Puppeteer and Chromium
RUN apt-get update && apt-get install -y \
    wget \
    ca-certificates \
    fonts-liberation \
    libasound2 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libxss1 \
    xdg-utils && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Chromium from Sparticuz
RUN npm install -g @sparticuz/chromium-min@131.0.1

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install Node.js dependencies, including Puppeteer
RUN npm install puppeteer@23.10.4 && npm install

# Copy the rest of the application code
COPY . ./

# Expose the application's port
EXPOSE 3000

# Define environment variables for Puppeteer
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

# Run the application
CMD ["npm", "start"]
